[workspace]
members = ["test"]

[package]
name = "ccc"
version = "0.0.0"
description = "A C++ utility library that provides modern C++ tools"
license = "MIT"
repo = "https://github.com/ZheFeng7110/ccc"

[build]
module_extensions = [".ccm"]
sources = ["modules/**/*.ccm"]
include_dirs = ["include"]

[lib]
path = "modules/ccc.ccm"

[targets.ccc]
kind = "lib"
